apiVersion: apps/v1
kind: Deployment

metadata:
  name: ippmis-postgres

spec:
  replicas: 1

  selector:
    matchLabels:
      app: ippmis-postgres

  template:
    metadata:
      labels:
        app: ippmis-postgres

    spec:
      containers:
      - name: postgres

        image: postgres:15

        ports:
        - containerPort: 5432

        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-storage

        env:
        - name: POSTGRES_USER
          value: appuser

        - name: POSTGRES_PASSWORD
          value: "1234"

        - name: POSTGRES_DB
          value: ippmis

      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc